# Generated by Django 5.0.4 on 2024-05-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_imagen'),
        ('estudiante', '0003_estudiante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='cursos', to='estudiante.estudiante'),
        ),
    ]
