# Generated by Django 5.0.4 on 2024-05-24 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso_estudiantes'),
        ('profesor', '0004_alter_profesor_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='profesor.profesor'),
        ),
    ]
