# Generated by Django 5.0.4 on 2024-05-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes'),
        ),
    ]
