# Generated by Django 5.0.4 on 2024-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
