# Generated by Django 5.0.4 on 2024-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_profesor_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
